# SPDX-License-Identifier: MIT
# Copyright (c) 2020 The Authors.

# Authors: Phu Tran          <@phudtran>

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fwds.zeta.com
spec:
  scope: Namespaced
  group: zeta.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Fwd
    plural: fwds
    singular: fwd
    shortNames:
      - fwd
      - fwds
  additionalPrinterColumns:
    - name: Status
      type: string
      priority: 0
      JSONPath: .spec.status
    - name: Dft
      type: string
      priority: 0
      JSONPath: .spec.dft
      description: The DFT that this Fwd is using
    - name: Droplet
      type: string
      priority: 0
      JSONPath: .spec.droplet
      description: The droplet where this fwd is deployed
    - name: CreateTime
      type: string
      priority: 0
      JSONPath: .spec.createtime
      description: Time the object is created
    - name: ProvisionDelay
      type: string
      priority: 0
      JSONPath: .spec.provisiondelay
      description: Time to provision an object from creation
